server.ssl.bundle: "demo"
server.port: 8443

spring:
  application:
    name: springboot-java21
  threads:
    virtual:
      enabled: true
  ssl.bundle.pem:
    demo:
      reload-on-update: true
      keystore:
        certificate: "certs/demo.crt"
        private-key: "certs/demo.key"
  banner:
    location: classpath:banner.txt
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
    prometheus:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true

logging:
  level:
    datasource-query-logger: INFO
    org.springframework.data: DEBUG