server.ssl.bundle: "demo"
server.port: 8443

spring:
  application:
    name: springboot-java21
  threads:
    virtual:
      enabled: true
  ssl.bundle.pem:
    demo:
      reload-on-update: true
      keystore:
        certificate: "certs/demo.crt"
        private-key: "certs/demo.key"
  banner:
    location: classpath:banner.txt
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  docker:
    compose:
      enabled: true
      file: docker-compose.yml

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
  tracing:
    sampling:
      probability: 1.0
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    datasource-query-logger: INFO
    org.springframework.data: DEBUG